# build stage
FROM golang:1.25.4-alpine3.21 AS builder
WORKDIR /app

# 先複製模組檔並下載依賴
COPY go.mod go.sum ./
RUN go mod download

# 複製整個專案
COPY . .

# 編譯 cmd/main.go，輸出到 /app/main
RUN go build -o main ./cmd

# final stage
FROM alpine:3.22
WORKDIR /app

# 從 builder 拷貝編譯好的可執行檔
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]

# TODO